---
title: "ITRDB references for PILA dating"
author: "D Perret"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      prompt = FALSE,
                      error = TRUE,
                      message = FALSE,
                      cache = FALSE,
                      cache.lazy = FALSE,
                      eval = TRUE,
                      eval.after = "fig.cap")

library(rmarkdown)
library(tidyverse)
library(rFIA)
library(ggplot2)
library(ggExtra)
library(rgdal)
library(sp)
library(ggsci)
library(raster)
library(splines)
library(lme4)
library(patchwork)
library(ade4)
library(adehabitatHR)
library(leaflet)
library(leafem)
library(htmlwidgets)


select <- dplyr::select

theme_set(theme_bw())
theme_update(text = element_text(size=16, color = "black"),
             panel.grid.major = element_blank(),
             panel.grid.minor = element_blank(),
             strip.background = element_blank(),
             panel.border=element_rect(size=1.5))

source("/Users/DanielPerret/Box/01. daniel.perret Workspace/PROJECTS/status_trends/growMort_rewrite.R")


old.proj <- '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs'

base.proj <- "+proj=aea +lat_0=23 +lon_0=-96 +lat_1=29.5 +lat_2=45.5 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"

states <- readOGR(dsn="/Users/DanielPerret/Box/01. daniel.perret Workspace/base_spatialdata/state_boundaries",
                  layer = "state_boundaries", verbose=F) %>% 
  spTransform(., CRSobj = CRS(base.proj))

range <- readOGR(dsn="/Users/DanielPerret/Box/01. daniel.perret Workspace/base_spatialdata/named_ranges",
                 layer = "lambertiana",
                 verbose = F,
                 p4s = old.proj) %>% 
  spTransform(., CRSobj = CRS(base.proj))
range.buff <- raster::buffer(x=range,width=150000)

```

## Sample site map with ITRDB chronologies

```{r}

itrdb <- FedData::get_itrdb(species=c("PSME","PILA","TSME","ABCO","ABAM",
                                      "ABMA","CADE","PIPO","PSMA"),label = "thispackagesucks3")

spat.itrdb <- itrdb$metadata %>% 
  filter(MEASUREMENT_TYPE == "Ring Width",
         CHRONOLOGY_TYPE == "Standard",
         END > 1980,
         START < 1900) %>% 
  sf::as_Spatial()
spat.itrdb$x <- spat.itrdb@coords[,1]
spat.itrdb$y <- spat.itrdb@coords[,2]

done.sites <- read.csv("/Users/DanielPerret/Box/01. daniel.perret Workspace/PROJECTS/sugarpine-status-trends/data/FIELD_DATA/site_data_complete_010924.csv", header=T) %>% 
  select(SITEID = Site.ID,
         ZONE = Niche.zone,
         STATE = State,
         LON = SITE.LON.calc,
         LAT = SITE.LAT.calc,
         FOREST = National.Forest,
         Site.Locality, Tree.Number, Recorder, Date)

spat.sites <- done.sites %>% 
  SpatialPointsDataFrame(coords = .[,c("LON","LAT")],
                         data=.,
                         proj4string = CRS(old.proj))

siteicon <- awesomeIcons(icon = "tree",
                      iconColor = "green",
                      library = "fa",
                      markerColor = "lightgray",
                      squareMarker = F)

itrdbicon0 <- awesomeIcons(icon = "laptop",
                      iconColor = "lightgreen",
                      library = "fa",
                      markerColor = "black",
                      squareMarker = F)

itrdbicon <- awesomeIcons(icon = "laptop",
                      iconColor = "yellow",
                      library = "fa",
                      markerColor = "black",
                      squareMarker = F)

itrdbicon2 <- awesomeIcons(icon = "laptop",
                      iconColor = "orange",
                      library = "fa",
                      markerColor = "black",
                      squareMarker = F)

map <- leaflet() %>% 
  # basemap groups
  addTiles(group = "OSM (default)") %>% 
  addProviderTiles(providers$Stamen.TonerLite, group = "Lite") %>% 
  addProviderTiles(providers$Esri.WorldTopoMap, group = "Topo") %>% 
  addAwesomeMarkers(data = spat.sites,
                    lng = ~LON, 
                    lat=~LAT, 
                    group = "PILA sites", 
                    popup= ~paste("SITE ID: ", SITEID),
                    icon = siteicon) %>% 
  addAwesomeMarkers(data = spat.itrdb %>% 
                      as.data.frame() %>% 
                      filter(SPECIES == "PILA"),
                    lng = ~x, 
                    lat=~y, 
                    group = "ITRDB chrons (PILA)", 
                    popup= ~paste("ITRDB: ", SERIES,
                                  "<br>Species: ", SPECIES,
                                  "<br>Start: ", START,
                                  "<br>End: ", END),
                    icon = itrdbicon0) %>% 
  addAwesomeMarkers(data = spat.itrdb %>% 
                      as.data.frame() %>% 
                      filter(!SPECIES %in% c("PIPO","PILA")),
                    lng = ~x, 
                    lat=~y, 
                    group = "ITRDB chrons (other)", 
                    popup= ~paste("ITRDB: ", SERIES,
                                  "<br>Species: ", SPECIES,
                                  "<br>Start: ", START,
                                  "<br>End: ", END),
                    icon = itrdbicon) %>% 
  addAwesomeMarkers(data = spat.itrdb %>% 
                      as.data.frame() %>% 
                      filter(SPECIES == "PIPO"),
                    lng = ~x, 
                    lat=~y, 
                    group = "ITRDB chrons (PIPO)", 
                    popup= ~paste("ITRDB: ", SERIES,
                                  "<br>Species: ", SPECIES,
                                  "<br>Start: ", START,
                                  "<br>End: ", END),
                    icon = itrdbicon2) %>% 
  addMouseCoordinates() %>% 
  setView(lng = -119.7,
          lat = 39,
          zoom = 6) %>% 
  addLayersControl(
    overlayGroups = c("PILA sites","ITRDB chrons (PILA)", "ITRDB chrons (other)", "ITRDB chrons (PIPO)"),
    baseGroups = c("OSM (default)", "Lite", "Topo"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>% 
  hideGroup(c("ITRDB chrons (PIPO)","ITRDB chrons (other)"))


saveWidget(widget = map,
           file = "PILAsites_itrdbchrons_9Jan24.html",
           selfcontained = TRUE)

map
```

